### ISSUE TITLE
cannnot resolve dependency

### ISSUE THREAD

**Issue by seraphr** [sqality/sbt-scct#15]
in sbt-scct 0.2, instrumentSettings contains a setting below

```
libraryDependencies += "com.github.scct" %% "scct" % "0.2-SNAPSHOT" % "scct"
```

but "0.2-SNAPSHOT" is deleted from maven repository.

**Comment by 0xRoch** [comment]
@seraphr you will need to add Sonatype's oss repository if you want to use Snapshots

```
resolvers +=
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```

**Comment by seraphr** [comment]
@D-Roch 

i cannot find "0.2-SNAPSHOT" in sonatype snapshots repository.
There is only "03-SNAPSHOT".

https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/scct_2.9.2/
https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/scct_2.10/

**Comment by gshakhn** [comment]
We were getting the same problem yesterday. For some reason, sbt was trying to download https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/scct_2.10/0.2-SNAPSHOT/scct_2.10-0.2-SNAPSHOT.jar, even though sbt-scct 0.2 requires scct 0.2 as far as I can tell (not the snapshot version). It was able to download the snapshot version today.

To be clear, we were depending on sbt-scct 0.2, not sbt-scct 0.2-SNAPSHOT.

**Comment by 0xRoch** [comment]
Ok I have republished everything and created a new branch to freeze 0.2 for scala-2.9.2
Let me know if it works for you.

**Comment by seraphr** [comment]
@D-Roch 

thanks for republishing.
now, I can resolve all dependencies!

**Comment by 0xRoch** [comment]
np sorry for the trouble
