### ISSUE TITLE
sbt-scct 0.2 doesn't work

### ISSUE THREAD

**Issue by mtgto** [sqality/sbt-scct#18]
hey

i'm using sbt-scct 0.2, which is depends on scct 0.2-SNAPSHOT (#16 was resolved, but [published binaries](https://oss.sonatype.org/content/repositories/releases/com/github/scct/sbt-scct_2.10_0.13/0.2/) still depends on SNAPSHOT version of sbt-scct).
Now, it is not work because there is not scct 0.2-SNAPSHOT in sonatype snapshot repository.
(There is ONLY 0.3-SNAPSHOT at https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/scct_2.10/ )

**Comment by 0xRoch** [comment]
Hi,

I have republished it, I have no idea why they keep disappearing,
You can also use the release : 

```
addSbtPlugin("com.github.scct" % "sbt-scct" % "0.2")
```

**Comment by mtgto** [comment]
It seems that [sbt-scct 0.2 is published at 1st, Oct](https://oss.sonatype.org/content/repositories/releases/com/github/scct/sbt-scct_2.10_0.13/0.2/), but #16 is solved at 11th, Oct.

I download [sbt-scct-0.2-sources.jar](https://oss.sonatype.org/content/repositories/releases/com/github/scct/sbt-scct_2.10_0.13/0.2/sbt-scct-0.2-sources.jar) and find `ScctPlugin.scala` still depends on scct 0.2-SNAPSHOT.

Could you check to be completed republishing?

**Comment by mtgto** [comment]
Sorry about my misunderstanding.
i found scct 0.2-SNAPSHOT. thanks!

**Comment by 0xRoch** [comment]
ok great, you can also use the 0.3-SNAPSHOT like in https://github.com/SCCT/scctSample
