### ISSUE TITLE
sbt-scct 0.2 doesn't work

### ISSUE THREAD

**Issue by dimbleby** [sqality/sbt-scct#19]
Exactly per #18: the published 0.2 depends on scct 0.2-SNAPSHOT, which keeps disappearing.

I see that (per #16) you've fixed the dependency in the code.  Can you perhaps publish an sbt-scct 0.2.1 with this fix?

Thanks!

**Comment by 0xRoch** [comment]
@dimbleby Ok you are right I'm starting a 0.2.1 release now, I'll let you know when the sync is completed with Maven Central.

**Comment by dimbleby** [comment]
Looks good - thanks!

**Comment by 0xRoch** [comment]
:+1:
